title: Nanziba Khan Biva
logo: nanziba_khan_biva_photo-modified.png
description: Machine Learning Enthusiast | Prospective PhD Candidate | IT Executive
email: nk.nanziba@gmail.com
theme: jekyll-theme-minimal
